name: api_requester_package
description: "This package is a simplified package for implementing requests to the server."
version: 0.0.1
homepage: https://pub.dev/packages/api_requester_package
repository: https://github.com/ShoshiDeveloper/api_requester_package

environment:
  sdk: '>=3.2.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  dio: ^5.4.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
